name: sign_shala
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+7

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get: ^4.6.6
  getwidget: ^4.0.0
  cached_network_image: ^3.4.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.7.0
  dio: ^5.6.0
  google_drive_wrapper: ^0.0.5
  line_icons: ^2.0.3
  youtube_player_flutter: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/humans/
    - assets/images/
